#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

feh --bg-scale ~/.walls/faded_nature.jpg

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1   # Use alt as the main modifier
Mod=Mod4    # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-w close_or_remove
hc keybind $Mod-Shift-w remove

hc keybind $Mod-Return spawn urxvt
#hc keybind $Mod-space spawn dmenu_run \
#    -dim 0.65 \
#    -b -q -i \
#    -h 32 -w 800 \
#    -x 16 -y 16 \
#    -p "exec_" \
#    -fn "Oswald:style=Medium" \
#    -nb "#09110A" \
#    -nf "#384622" \
#    -sb "#222317" \
#    -sf "#76874D"
hc keybind $Mod-space spawn dmenu_run -i -b -q -dim 0.65 -y 635 -x 490 -l 10 -w 300 -p "exec_" -nb "#09110A" -nf "#384622" -sb "#222317" -sf "#76874D"

# basic movement
# focusing clients
hc keybind $Mod-h           focus left
hc keybind $Mod-j           focus down
hc keybind $Mod-k           focus up
hc keybind $Mod-l           focus right
hc keybind $Mod-Tab         cycle_all +1

# moving clients
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-Ctrl-h	split   left	0.5
hc keybind $Mod-Ctrl-j	split	bottom	0.5
hc keybind $Mod-Ctrl-k	split	up	0.5
hc keybind $Mod-Ctrl-l	split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-Return split explode

# resizing frames
resizestep=0.01
hc keybind $Mod-Mod1-h       resize left +$resizestep
hc keybind $Mod-Mod1-j       resize down +$resizestep
hc keybind $Mod-Mod1-k       resize up +$resizestep
hc keybind $Mod-Mod1-l       resize right +$resizestep

# rotating frames
hc keybind $Mod-period	chain .-. lock .-. rotate .-. rotate .-. rotate .-. unlock
hc keybind $Mod-comma	rotate

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# layouting
#hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-Shift-f floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# padding
hc pad 0 8 8 8 8

# theme
hc set frame_border_active_color '#303030'
hc set frame_border_normal_color '#1f1f22'
hc set frame_bg_active_color '#303033'
hc set frame_bg_normal_color '#1f1f22'
hc set frame_border_width 2
hc set always_show_frame 0
hc set frame_gap 0
hc set frame_bg_transparent 1
hc set frame_active_opacity 25
hc set frame_normal_opacity 0

hc set window_border_active_color '#303033'
hc set window_border_normal_color '#1f1f22'
hc set window_border_urgent_color '#4cdcd4'
hc set window_border_width 1
hc set window_border_inner_width 0
hc set window_gap 0

hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

hc set frame_padding 8
hc set snap_gap 16
hc set snap_distance 30

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    "$panel" $monitor &
#done
